# Generated by Django 3.1 on 2021-08-27 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_auto_20210825_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название проекта')),
                ('repo_url', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('text', models.TextField(blank=True, max_length=400, verbose_name='текст заметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='userapp.user', verbose_name='создал пользователь')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todoapp.project', verbose_name='связанный проект')),
            ],
        ),
    ]
