# Generated by Django 3.1 on 2021-09-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название проекта')),
                ('repo_url', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст заметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='todoapp.project', verbose_name='связанный проект')),
            ],
        ),
    ]
